### PR TITLE
Changes to compile on Linux

### PR DESCRIPTION
**Pull request by pleroy**

### CODE REVIEW

**Comment by lamont-granquist** [comment]
stops now at:

```
In file included from astronomy/standard_product_3.cpp:1:
In file included from ./astronomy/standard_product_3.hpp:9:
In file included from ./astronomy/frames.hpp:6:
In file included from ./geometry/frame.hpp:8:
In file included from ./geometry/named_quantities.hpp:6:
In file included from ./geometry/affine_map.hpp:4:
In file included from ./geometry/point.hpp:138:
In file included from ./geometry/point_body.hpp:10:
In file included from ./geometry/grassmann.hpp:9:
./geometry/r3_element.hpp:64:5: warning: anonymous structs are a GNU extension [-Wgnu-anonymous-struct]
    struct {
    ^
./geometry/r3_element.hpp:69:5: warning: anonymous structs are a GNU extension [-Wgnu-anonymous-struct]
    struct {
    ^
./geometry/r3_element.hpp:64:5: warning: anonymous types declared in an anonymous union are an extension [-Wnested-anon-types]
    struct {
    ^
./geometry/r3_element.hpp:69:5: warning: anonymous types declared in an anonymous union are an extension [-Wnested-anon-types]
    struct {
    ^
astronomy/standard_product_3.cpp:44:40: error: no member named 'string' in 'std::filesystem::path'
      location = absl::StrCat(filename.string(), " at end of file");
                              ~~~~~~~~ ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
12 warnings and 2 errors generated.
make: *** [obj/astronomy/standard_product_3.o] Error 1
```

**Comment by pleroy** [comment]
It looks like https://github.com/mockingbirdnest/Compatibility/blob/master/filesystem/filesystem is missing the `string` function.  One day, I'm sure, Apple will support C++17...

**Comment by pleroy** [comment]
https://github.com/mockingbirdnest/Compatibility/commit/56863976c623b6f332d07a5290557baf2ba4e910 should help.  @eggrobin is going to try it.

**Comment by pleroy** [comment]
@lamont-granquist: I am told that with the above change it builds on Mac.  You'll need to pull the `Compatibility` repository.

**Pull request merged**
