### PR TITLE
Minor Russian Localization Changes

### PR DESCRIPTION
**Pull request by Pl3aseJust3ndMySuffering**
Made some grammar corrections.

### CODE REVIEW

**Comment by Test-Account-KSP** [comment]
#Principia_PlottingFrame = карты
    #Principia_PlottingFrame = Система Координат
I don't think this will work correctly. It is not meant to be a translation of "Reference Frame" in Russian. It is about the distinction between "maneuver frame" and "plotting frame", so I think the change will replace "система координат карты" with "система координат Система Координат", which is definitely not intended and makes no sense.
    
    #Principia_ReferenceFrameSelector_Description_Target = Цель, аппарат <<1>>, неподвижна.\nПлоскость орбиты цели вокруг <<gen:2>> горизонтальна.\nСистема координат вращается вместе с орбитой, фиксируя направление на <<pre:2>>.
    #Principia_ReferenceFrameSelector_Description_Target = Цель, аппарат <<1>>, неподвижны.\nПлоскость орбиты цели вокруг <<gen:2>> горизонтальна.\nСистема координат вращается вместе с орбитой, фиксируя направление на <<pre:2>>
This change is incorrect. The meaning is " The target, vessel <<1>>, is fixed. ", not "The target and vessel <<1>> are fixed".  Vessel <<1>> IS the target.

    #Principia_OrbitAnalyser_Warning_NoPrimary = <<1>> гравитационно не привязан в течение <<2>>  // <<2>>mission_duration.FormatDuration <<1>> vessel name
    #Principia_OrbitAnalyser_AnalysisDescription = Орбита <<gen:1>> вокруг <<gen:2>> в течение <<3>>:\n<<4>>  // <<1>> vessel name <<2>> centre body <<3>> time <<4>> result
    #Principia_OrbitAnalyser_Warning_NoPrimary = <<1>> гравитационно не привязан в течении <<2>>  // <<2>>mission_duration.FormatDuration <<1>> vessel name
    #Principia_OrbitAnalyser_AnalysisDescription = Орбита <<gen:1>> вокруг <<gen:2>> в течении <<3>>:\n<<4>>  // <<1>> vessel name <<2>> centre body <<3>> time <<4>> result
This change is wrong according to (convoluted) Russian grammar. Correct is "в течение".

    #Principia_FlightPlan_StatusMessage_Infinite = манёвр #<<1>> привёл бы к бесконечной или неопределенной скорости  // <<1>> Error Manœuvre
    #Principia_FlightPlan_StatusMessage_Infinite = манёвр #<<1>> приведёт к бесконечной или неопределенной скорости  // <<1>> Error Manœuvre
This change is not the exact translation. The sentence is about something that cannot or should not happen, which I think explains the choice of tense in the English version ("would result in an infinite or indeterminate velocity", not "will result...").

**Comment by Pl3aseJust3ndMySuffering** [comment]
> 

Alright, I agree with you on the first and second one.

> #Principia_OrbitAnalyser_Warning_NoPrimary = <<1>> гравитационно не привязан в течение <<2>>  // <<2>>mission_duration.FormatDuration <<1>> vessel name
#Principia_OrbitAnalyser_AnalysisDescription = Орбита <<gen:1>> вокруг <<gen:2>> в течение <<3>>:\n<<4>>  // <<1>> vessel name <<2>> centre body <<3>> time <<4>> result
This probably should be rephrased. I'll try to think of something after my morning nap. Thanks for pointing it out though, I suppose I was using 'течение' wrong my entire life.

> #Principia_FlightPlan_StatusMessage_Infinite = манёвр #<<1>> привёл бы к бесконечной или неопределенной скорости  // <<1>> Error Manœuvre
We can probably rephrase it like this: "конечная скорость манёвра #<<1>> бесконечна или не определена.". It's easy to read and signals that something is wrong.

**Comment by Test-Account-KSP** [comment]
"конечная скорость манёвра #<<1>> бесконечна или не определена." - means "the velocity of maneuver #1 is infinite or indeterminate", but a maneuver doesn't have a velocity, a vessel has...

**Comment by eggrobin** [comment]
The English source for the stuff under `#Principia_MainWindow_Declutter` is getting reworded backward, and it sounds like there are issues with the other translations, so I am going to close this for now; let’s discuss this further in the discord.

**Pull request closed without merging**
