### PR TITLE
Turn loop variable copies to references

### PR DESCRIPTION
**Pull request by aw1621107**
I was less certain that these changes were right, so each file changed got its own commit to help with future bisecting.

### CODE REVIEW

**Comment by pleroy** [comment]
Can one of the admins verify this patch?

**Comment by eggrobin** [comment]
As discussed on IRC, we don't use `not_null<T*> const&`, on the other hand we try to make those explicit rather than `auto`, precisely so we aren't tempted to add a `&`, so it might be a good idea to change those that use auto, for consistency (e.g., PileUp has both `auto const` and `not_null<Part*> const` for iterating on `parts_`.

**Comment by pleroy** [comment]
ok to test

**Comment by pleroy** [comment]
ok to test

**Comment by pleroy** [comment]
Thanks for all your contributions.  Much appreciated.

**Pull request merged**
